### ISSUE TITLE
I can't create stale translations

### ISSUE THREAD

**Issue by annakrassa** [andrewhancox/moodle-filter_translations#51]
I can't create any stale translation....
I am translating some text in Greek.
Then I am editing the text (English text) and saving.
The text automatically returns to English (as in the old translation plugin)
And when I am checking the Stale translations in that page I get a message saying "nothing to display".

**Comment by jgramp** [comment]
AFAIK the code to apply the span to existing content to enable the
detection of stale translations is yet to be implemented. Andrew can
confirm. Once this exists it should resolve this issue though.

**Comment by andrewhancox** [comment]
There is a CLI tool available to do this - please use with extreme caution...
php cli/insert_spans.php

**Comment by jgramp** [comment]
Thanks Andrew. So every time we restore a Moodle course we need to run the cli tool?

When you say "use with extreme caution" we can certainly backup our site beforehand, but what are the potential risks of using this tool?

Would it be feasible for a user interface to be added to this function (for site admins) without too much hassle?

**Comment by andrewhancox** [comment]
I built this tool as something that would be run as a one-off... it would not be feasible to constrain it to a specific course, it also may have unpredictable effects as we still don't know if some plugins/areas may have issues with the span tags.
If you need it applied to courses that are restored from backup I would say we should handle that differently.

**Comment by jgramp** [comment]
Thanks Andrew.

How would you suggest restored courses are handled in that case?

**Comment by andrewhancox** [comment]
I’m not sure, there are a lot of ways plug-ins can hook in to the restore process so we may well be able to handle it that way. I’ll have a think while I’m on holiday.
